Update torbrowser-launcher to 0.3.5
flathub/com.github.micahflee.torbrowser-launcher pull request #24
Opened 2021-06-21 03:23 UTC by micahflee

Fixes #21

2021-06-21 10:08 UTC, AsciiWolf requested changes

2021-06-21 10:08 UTC, AsciiWolf commented on com.github.micahflee.torbrowser-launcher.yaml
>          paths:
```suggestion
        path: use-flatpak-sys-prefix.patch
```

2021-06-21 10:08 UTC, AsciiWolf commented on com.github.micahflee.torbrowser-launcher.yaml
>            - use-flatpak-sys-prefix.patch
```suggestion
```

2021-06-21 10:11 UTC, AsciiWolf commented
Thanks! I see that you forgot to bump the version [in AppStream metadata](https://github.com/micahflee/torbrowser-launcher/blob/develop/share/metainfo/torbrowser.appdata.xml#L32). Any chance you could redo the 0.3.5 tag with this fixed?

2021-06-22 01:53 UTC, micahflee commented
Okay, this one should be good I think.

2021-06-22 12:08 UTC, merged

2021-06-22 12:08 UTC, AsciiWolf commented
Thanks!